//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.PayLoans = new HashSet<PayLoan>();
        }
    
        public long LoanAccountNo { get; set; }
        public int LoanId { get; set; }
        public string Occupation { get; set; }
        public int AnnualIncome { get; set; }
        public int LoanAmount { get; set; }
        public byte Duration { get; set; }
        public long AccountNo { get; set; }
        public Nullable<decimal> EMI { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string Status { get; set; }
        public string FinalStatus { get; set; }
        public string PresentAddress { get; set; }
        public Nullable<int> PayAmount { get; set; }
    
        public virtual LoanProgram LoanProgram { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayLoan> PayLoans { get; set; }
    }
}
