//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayLoan
    {
        public int PaymentId { get; set; }
        public long LoanAccountNo { get; set; }
        public int Amount { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public int TotalLoan { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
